# Generated by Django 5.2.17 on 2026-09-15 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='advertisements.advertisement', verbose_name='Рекламная кампания')),
            ],
            options={
                'verbose_name': 'Потенциальный клиент',
                'verbose_name_plural': 'Потенциальные клиенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
