[mypy]
plugins = mypy_django_plugin.main
ignore_missing_imports = True
exclude = (migrations/|manage\.py)

[mypy.plugins.django-stubs]
django_settings_module = crm_system.settings

[mypy-*.migrations.*]
ignore_errors = True
