# Generated by Django 5.2.17 on 2026-09-15 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('document', models.FileField(upload_to='contracts/', verbose_name='Документ')),
                ('start_date', models.DateField(verbose_name='Дата заключения')),
                ('end_date', models.DateField(verbose_name='Действует до')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='products.product', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
                'ordering': ['-start_date'],
            },
        ),
    ]
